name: "Xavier's Blog"
description: "Detailed In This Chapter by Weixiang Zhang"

url: "http://127.0.0.1:4000"
loadingImg: "http://127.0.0.1:4000/img/loading.gif"
filePath: "http://127.0.0.1:4000/img/"

timezone: Asia/Hangzhou

paginate: 20

highlighter: pygments

markdown: rdiscount
permalink: pretty
gems: [jekyll-paginate]